/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author DO
 */
public class PanelNhapDuLieu extends javax.swing.JPanel {

    /**
     * Creates new form ManHinhThemDuLieu
     */
    
    private controller.LopHocController lopCtrl = new controller.LopHocController();
    private controller.GiangVienController gvCtrl = new controller.GiangVienController();
    private controller.SinhVienController svCtrl = new controller.SinhVienController();
    
    /** Callback được gọi sau khi thêm dữ liệu thành công để các panel khác tự refresh */
    private Runnable onDataChanged;
    
   public PanelNhapDuLieu() {
        this(null);
    }
    
    public PanelNhapDuLieu(Runnable onDataChanged) {
        this.onDataChanged = onDataChanged;
        initComponents();
        setLayout(new java.awt.BorderLayout());
        add(jPanel2, java.awt.BorderLayout.CENTER);
        setupComboBoxes();
        
        // Auto-reload dữ liệu khi tab được bật
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentShown(java.awt.event.ComponentEvent evt) {
                setupComboBoxes();
            }
        });
    }
    
    /** Gọi callback thông báo dữ liệu đã thay đổi (chạy trên EDT) */
    private void notifyDataChanged() {
        setupComboBoxes();
        if (onDataChanged != null) {
            javax.swing.SwingUtilities.invokeLater(onDataChanged);
        }
    }
    
    private void setupComboBoxes() {
        String[] dsKhoa = {"Công nghệ Thông tin và Truyền thông", "Điện - Điện tử", "Cơ khí - Ô tô", "Kinh tế", "Ngoại ngữ - Du lịch"};
        cboKhoaLop.setModel(new javax.swing.DefaultComboBoxModel<>(dsKhoa));
        cboKhoaGV.setModel(new javax.swing.DefaultComboBoxModel<>(dsKhoa));
        cboKhoaSV.setModel(new javax.swing.DefaultComboBoxModel<>(dsKhoa));

        // ✅ Cập nhật: Làm mới controller và lấy danh sách lớp học chuẩn MVC
        lopCtrl.reload();
        cboLopSV.removeAllItems();
        for (model.LopHoc lop : lopCtrl.getDanhSachLop()) {
            cboLopSV.addItem(lop.getTenLop());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtHoTenSV = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cboKhoaSV = new javax.swing.JComboBox<>();
        cboLopSV = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        txtEmailSV = new javax.swing.JTextField();
        btnLamMoiSV = new javax.swing.JButton();
        btnThemSV = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaLop = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTenLop = new javax.swing.JTextField();
        btnLamMoiLop = new javax.swing.JButton();
        btnThemLop = new javax.swing.JButton();
        cboKhoaLop = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtMaGV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtHoTenGV = new javax.swing.JTextField();
        btnLamMoiGV = new javax.swing.JButton();
        btnThemGV = new javax.swing.JButton();
        cboKhoaGV = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtEmailGV = new javax.swing.JTextField();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NHẬP DỮ LIỆU");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel1)
                .addContainerGap(309, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jLabel13.setText("Mã SV:");

        txtMaSV.addActionListener(this::txtMaSVActionPerformed);

        jLabel14.setText("Khoa:");

        jLabel15.setText("Họ tên:");

        txtHoTenSV.addActionListener(this::txtHoTenSVActionPerformed);

        jLabel16.setText("Lớp:");

        cboKhoaSV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboLopSV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel17.setText("Email:");

        btnLamMoiSV.setText("Làm mới");
        btnLamMoiSV.addActionListener(this::btnLamMoiSVActionPerformed);

        btnThemSV.setText("Thêm");
        btnThemSV.addActionListener(this::btnThemSVActionPerformed);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(cboKhoaSV, 0, 127, Short.MAX_VALUE)
                    .addComponent(txtMaSV)
                    .addComponent(jLabel17)
                    .addComponent(txtEmailSV))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnLamMoiSV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThemSV))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel16)
                        .addComponent(jLabel15)
                        .addComponent(txtHoTenSV, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addComponent(cboLopSV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboKhoaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboLopSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmailSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLamMoiSV)
                    .addComponent(btnThemSV))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sinh viên", jPanel8);

        jLabel2.setText("Mã lớp:");

        txtMaLop.addActionListener(this::txtMaLopActionPerformed);

        jLabel3.setText("Khoa:");

        jLabel4.setText("Tên lớp:");

        txtTenLop.addActionListener(this::txtTenLopActionPerformed);

        btnLamMoiLop.setText("Làm mới");
        btnLamMoiLop.addActionListener(this::btnLamMoiLopActionPerformed);

        btnThemLop.setText("Thêm");
        btnThemLop.addActionListener(this::btnThemLopActionPerformed);

        cboKhoaLop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnLamMoiLop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThemLop))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(cboKhoaLop, 0, 127, Short.MAX_VALUE)
                            .addComponent(txtMaLop))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(299, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboKhoaLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLamMoiLop)
                    .addComponent(btnThemLop))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lớp học", jPanel4);

        jLabel6.setText("Mã GV:");

        txtMaGV.addActionListener(this::txtMaGVActionPerformed);

        jLabel7.setText("Khoa:");

        jLabel8.setText("Họ tên:");

        txtHoTenGV.addActionListener(this::txtHoTenGVActionPerformed);

        btnLamMoiGV.setText("Làm mới");
        btnLamMoiGV.addActionListener(this::btnLamMoiGVActionPerformed);

        btnThemGV.setText("Thêm");
        btnThemGV.addActionListener(this::btnThemGVActionPerformed);

        cboKhoaGV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setText("Email:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(cboKhoaGV, 0, 127, Short.MAX_VALUE)
                    .addComponent(txtMaGV))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnLamMoiGV)
                        .addGap(18, 18, 18)
                        .addComponent(btnThemGV))
                    .addComponent(jLabel8)
                    .addComponent(txtHoTenGV, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailGV, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoTenGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboKhoaGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLamMoiGV)
                    .addComponent(btnThemGV))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Giảng viên", jPanel7);

        jPanel2.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaLopActionPerformed

    private void txtTenLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenLopActionPerformed

    private void btnLamMoiLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiLopActionPerformed
        // TODO add your handling code here:
        txtMaLop.setText("");
        txtTenLop.setText("");
        if (cboKhoaLop.getItemCount() > 0) cboKhoaLop.setSelectedIndex(0);
        txtMaLop.requestFocus();
        
    }//GEN-LAST:event_btnLamMoiLopActionPerformed

    private void btnThemLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLopActionPerformed
        // TODO add your handling code here:
        if (txtMaLop.getText().trim().isEmpty() || txtTenLop.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin Lớp học!");
            return;
        }
        try {
            String khoa = cboKhoaLop.getSelectedItem().toString();
            String gvcn = ""; // Mặc định chưa có GVCN khi mới thêm lớp
            lopCtrl.themLop(txtMaLop.getText().trim(), txtTenLop.getText().trim(), khoa, gvcn);
            
            javax.swing.JOptionPane.showMessageDialog(this, "Thêm Lớp học thành công!");
            btnLamMoiLopActionPerformed(evt);
            notifyDataChanged();
        } catch (IllegalArgumentException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage());
        }
        
    }//GEN-LAST:event_btnThemLopActionPerformed
    
    private void txtMaGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaGVActionPerformed

    private void txtHoTenGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenGVActionPerformed

    private void btnLamMoiGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiGVActionPerformed
        // TODO add your handling code here:
        txtMaGV.setText("");
        txtHoTenGV.setText("");
        txtEmailGV.setText("");
        if (cboKhoaGV.getItemCount() > 0) cboKhoaGV.setSelectedIndex(0);
        txtMaGV.requestFocus();
        
    }//GEN-LAST:event_btnLamMoiGVActionPerformed

    private void btnThemGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemGVActionPerformed
        // TODO add your handling code here:
        String email = txtEmailGV.getText().trim();
        if (txtMaGV.getText().trim().isEmpty() || txtHoTenGV.getText().trim().isEmpty() || email.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
            return;
        }
        if (!email.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Email sai định dạng!");
            return;
        }
        try {
            String khoa = cboKhoaGV.getSelectedItem().toString();
            gvCtrl.themGiangVien(txtMaGV.getText().trim(), txtHoTenGV.getText().trim(), "Chưa cập nhật", email, khoa);
            javax.swing.JOptionPane.showMessageDialog(this, "Thêm Giảng viên thành công!");
            btnLamMoiGVActionPerformed(evt);
            notifyDataChanged();
        } catch (IllegalArgumentException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage());
        }
        
    }//GEN-LAST:event_btnThemGVActionPerformed

    private void txtHoTenSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenSVActionPerformed

    private void txtMaSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSVActionPerformed

    private void btnLamMoiSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiSVActionPerformed
        // TODO add your handling code here:
        txtMaSV.setText("");
        txtHoTenSV.setText("");
        txtEmailSV.setText("");
        if (cboKhoaSV.getItemCount() > 0) cboKhoaSV.setSelectedIndex(0);
        if (cboLopSV.getItemCount() > 0) cboLopSV.setSelectedIndex(0);
        txtMaSV.requestFocus();
    }//GEN-LAST:event_btnLamMoiSVActionPerformed

    private void btnThemSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSVActionPerformed
        // TODO add your handling code here:
        String email = txtEmailSV.getText().trim();
        if (txtMaSV.getText().trim().isEmpty() || txtHoTenSV.getText().trim().isEmpty() || email.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
            return;
        }
        if (!email.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Email sai định dạng!");
            return;
        }
        try {
            String khoa = cboKhoaSV.getSelectedItem().toString();
            String lop = cboLopSV.getSelectedItem() != null ? cboLopSV.getSelectedItem().toString() : "Chưa có";
            svCtrl.themSinhVien(txtMaSV.getText().trim(), txtHoTenSV.getText().trim(), email, khoa, lop);
            javax.swing.JOptionPane.showMessageDialog(this, "Thêm Sinh viên thành công!");
            btnLamMoiSVActionPerformed(evt);
            notifyDataChanged();
        } catch (IllegalArgumentException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnThemSVActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoiGV;
    private javax.swing.JButton btnLamMoiLop;
    private javax.swing.JButton btnLamMoiSV;
    private javax.swing.JButton btnThemGV;
    private javax.swing.JButton btnThemLop;
    private javax.swing.JButton btnThemSV;
    private javax.swing.JComboBox<String> cboKhoaGV;
    private javax.swing.JComboBox<String> cboKhoaLop;
    private javax.swing.JComboBox<String> cboKhoaSV;
    private javax.swing.JComboBox<String> cboLopSV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtEmailGV;
    private javax.swing.JTextField txtEmailSV;
    private javax.swing.JTextField txtHoTenGV;
    private javax.swing.JTextField txtHoTenSV;
    private javax.swing.JTextField txtMaGV;
    private javax.swing.JTextField txtMaLop;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtTenLop;
    // End of variables declaration//GEN-END:variables
}
