/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JButton;
import model.TaiKhoan;


public class sideBarPanel extends javax.swing.JPanel {
    
    public interface SidebarListener {
     void onMenuSelected(String tenManHinh);
}
    private SidebarListener listener;
    
    private final java.awt.Color MAU_CHON = new java.awt.Color(0, 122, 255);
    private final java.awt.Color MAU_CHU_CHON = java.awt.Color.WHITE;
    private final java.awt.Color MAU_MAC_DINH = new java.awt.Color(240, 240, 240);
    private final java.awt.Color MAU_CHU_MAC_DINH = java.awt.Color.BLACK;
    
    private javax.swing.JButton btnHienTai = null;
    
    public sideBarPanel(SidebarListener listener, TaiKhoan tk) {
        initComponents();
        this.listener = listener;
        btnTongQuan.addActionListener(this::btnTongQuanActionPerformed);
        btnChucNang.addActionListener(this::btnChucNangActionPerformed);
        btnHienThiDanhSach.addActionListener(this::btnHienThiDanhSachActionPerformed);
        btnNhapDuLieu.addActionListener(this::btnNhapDuLieuActionPerformed);
        setPreferredSize(new java.awt.Dimension(220, 0));
        lblEmail.setText(tk.getEmail());
        lblHoTen.setText(tk.getHoTen());
    }
    
    public void phanQuyenGiaoVien() {
        if (btnNhapDuLieu != null) {
            btnNhapDuLieu.setEnabled(false); 
            btnNhapDuLieu.setVisible(false);
        }

        if (btnChucNang != null) {
            btnChucNang.setEnabled(false);
            btnChucNang.setVisible(false);
        }
    }
    
    private void doiMauNutChon(JButton btnDuocBam) {
        if (btnHienTai != null) {
            btnHienTai.setBackground(MAU_MAC_DINH);
            btnHienTai.setForeground(MAU_CHU_MAC_DINH);
            btnHienTai.setOpaque(false);
        }
        
        btnHienTai = btnDuocBam;
        btnHienTai.setOpaque(true);
        btnHienTai.setContentAreaFilled(true);
        btnHienTai.setBackground(MAU_CHON);
        btnHienTai.setForeground(MAU_CHU_CHON);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblHoTen = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 0));
        btnTongQuan = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnNhapDuLieu = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnHienThiDanhSach = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btnChucNang = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnDangXuat = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setAlignmentX(0.0F);
        setPreferredSize(new java.awt.Dimension(250, 150));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 80));
        jPanel1.setPreferredSize(new java.awt.Dimension(32767, 80));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new java.awt.GridLayout(2, 1, 1, 0));

        lblHoTen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHoTen.setText("họ tên tk");
        lblHoTen.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 1, 1));
        jPanel2.add(lblHoTen);

        lblEmail.setText("gmail");
        lblEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 15, 1));
        jPanel2.add(lblEmail);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1);
        add(filler2);

        btnTongQuan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTongQuan.setText("Tổng quan");
        btnTongQuan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        btnTongQuan.setBorderPainted(false);
        btnTongQuan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTongQuan.setFocusPainted(false);
        btnTongQuan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTongQuan.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnTongQuan.setMaximumSize(new java.awt.Dimension(32767, 55));
        btnTongQuan.addActionListener(this::btnTongQuanActionPerformed);
        add(btnTongQuan);

        jSeparator1.setMaximumSize(new java.awt.Dimension(32767, 2));
        jSeparator1.setPreferredSize(new java.awt.Dimension(250, 2));
        add(jSeparator1);

        btnNhapDuLieu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNhapDuLieu.setText("Nhập/Thêm dữ liệu");
        btnNhapDuLieu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        btnNhapDuLieu.setBorderPainted(false);
        btnNhapDuLieu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhapDuLieu.setFocusPainted(false);
        btnNhapDuLieu.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnNhapDuLieu.setMaximumSize(new java.awt.Dimension(32767, 55));
        btnNhapDuLieu.addActionListener(this::btnNhapDuLieuActionPerformed);
        add(btnNhapDuLieu);

        jSeparator2.setMaximumSize(new java.awt.Dimension(32767, 2));
        jSeparator2.setPreferredSize(new java.awt.Dimension(250, 2));
        add(jSeparator2);

        btnHienThiDanhSach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHienThiDanhSach.setText("Hiển thị dữ liệu");
        btnHienThiDanhSach.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        btnHienThiDanhSach.setBorderPainted(false);
        btnHienThiDanhSach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHienThiDanhSach.setFocusPainted(false);
        btnHienThiDanhSach.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnHienThiDanhSach.setMaximumSize(new java.awt.Dimension(32767, 55));
        btnHienThiDanhSach.addActionListener(this::btnHienThiDanhSachActionPerformed);
        add(btnHienThiDanhSach);

        jSeparator3.setMaximumSize(new java.awt.Dimension(32767, 2));
        jSeparator3.setPreferredSize(new java.awt.Dimension(250, 2));
        add(jSeparator3);

        btnChucNang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChucNang.setText("Các chức năng xử lí");
        btnChucNang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        btnChucNang.setBorderPainted(false);
        btnChucNang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChucNang.setFocusPainted(false);
        btnChucNang.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnChucNang.setMaximumSize(new java.awt.Dimension(32767, 55));
        btnChucNang.addActionListener(this::btnChucNangActionPerformed);
        add(btnChucNang);

        jSeparator4.setMaximumSize(new java.awt.Dimension(32767, 2));
        jSeparator4.setPreferredSize(new java.awt.Dimension(250, 2));
        add(jSeparator4);
        add(filler1);

        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        btnDangXuat.setBorderPainted(false);
        btnDangXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangXuat.setFocusPainted(false);
        btnDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnDangXuat.setMaximumSize(new java.awt.Dimension(32767, 55));
        btnDangXuat.addActionListener(this::btnDangXuatActionPerformed);
        add(btnDangXuat);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTongQuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTongQuanActionPerformed
        doiMauNutChon(btnTongQuan);
        if (listener != null) listener.onMenuSelected("MAN_HINH_CHINH");
    }//GEN-LAST:event_btnTongQuanActionPerformed

    private void btnHienThiDanhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiDanhSachActionPerformed
        doiMauNutChon(btnHienThiDanhSach);
        if (listener != null) listener.onMenuSelected("HIEN_THI");
    }//GEN-LAST:event_btnHienThiDanhSachActionPerformed

    private void btnChucNangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChucNangActionPerformed
        doiMauNutChon(btnChucNang); 
        if (listener != null) listener.onMenuSelected("XU_LY");
    }//GEN-LAST:event_btnChucNangActionPerformed

    private void btnNhapDuLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapDuLieuActionPerformed
        doiMauNutChon(btnNhapDuLieu);
        if (listener != null) listener.onMenuSelected("NHAP_DU_LIEU");
    }//GEN-LAST:event_btnNhapDuLieuActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Bạn có chắc chắn muốn đăng xuất khỏi hệ thống?", 
            "Xác nhận đăng xuất", 
            javax.swing.JOptionPane.YES_NO_OPTION);
            
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // Tắt màn hình chính hiện tại
            javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
            // Mở lại màn hình Đăng Nhập
            new ManHinhDangNhap().setVisible(true);
        }
    }//GEN-LAST:event_btnDangXuatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChucNang;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnHienThiDanhSach;
    private javax.swing.JButton btnNhapDuLieu;
    private javax.swing.JButton btnTongQuan;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblHoTen;
    // End of variables declaration//GEN-END:variables
}
